name: autoshut
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  process_run: ^1.1.0
  intl: ^0.18.0
  flutter_local_notifications: ^17.2.3
  tray_manager: ^0.2.4
  get: ^4.6.6
  get_storage: ^2.1.1
  window_manager: ^0.4.2
  bitsdojo_window: ^0.1.6
  url_launcher: ^6.3.0
  http: ^1.2.2
  windows_single_instance: ^1.0.1
  flutter_timer_countdown: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
assets:
  - assets/images/autoshut.ico